export const jobs = [
  {
    id: 1,
    title: "MERN Stack Trainee",
    logo: "/logo4.webp",
    openingDate: "2025-09-15",
    closingDate: "2025-11-30",
    description:
      "As a MERN Stack Trainee, you will learn and work on full-stack web development projects using MongoDB, Express, React, and Node.js. You will gain hands-on experience in building dynamic web applications, understanding REST APIs, managing databases, and deploying applications. This role is perfect for individuals who are eager to learn modern web technologies, improve problem-solving skills, and collaborate with a team of developers to create real-world solutions.",
    requirements: [
      "Good understanding of HTML, CSS, JavaScript",
      "Basic knowledge of React and Node.js",
      "Willingness to learn new technologies quickly",
      "Strong problem-solving and debugging skills",
      "Ability to work in a team environment",
    ],
    skills: [
      "MongoDB: Schema design, CRUD operations, indexing",
      "Express.js: Middleware, routing, RESTful APIs",
      "React.js: Components, hooks, state management, routing",
      "Node.js: Event-driven architecture, asynchronous programming",
      "Version Control: Git, GitHub collaboration",
      "Frontend & Backend Integration",
      "Deployment: Heroku, Vercel, or similar platforms",
      "Debugging and testing",
      "Understanding of MVC architecture",
    ],
    email: "hr@ibnsu.com",
  },
  {
    id: 2,
    title: "VFX Trainee",
    logo: "/uplogo1.webp",
    openingDate: "2025-09-15",
    closingDate: "2025-11-30",
    description:
      "As a VFX Trainee, you will assist in creating stunning visual effects for films, advertisements, and other media. You will learn to combine live-action footage with digital effects, work with layers, compositing, motion graphics, and create animations that bring stories to life. The role involves understanding the principles of visual storytelling, color correction, and using industry-standard software to create high-quality visual effects.",
    requirements: [
      "Basic knowledge of Adobe After Effects, Photoshop or similar tools",
      "Creativity and attention to detail",
      "Understanding of visual storytelling and cinematic techniques",
      "Ability to follow project briefs and timelines",
      "Willingness to learn advanced VFX techniques",
    ],
    skills: [
      "Adobe After Effects: Compositing, keying, motion tracking",
      "Photoshop: Image editing, color correction, layering",
      "Cinema 4D / Blender: 3D modeling and animation",
      "Animation principles: Timing, motion, physics",
      "Green screen compositing",
      "Video editing and post-production",
      "Visual storytelling and cinematic effects",
      "Attention to detail and creativity",
      "Team collaboration and feedback implementation",
    ],
    email: "hr@ibnsu.com",
  },
  {
    id: 3,
    title: "Digital Marketing Trainee",
    logo: "/uplogo3.webp",
    openingDate: "2025-09-15",
    closingDate: "2025-11-30",
    description:
      "As a Digital Marketing Trainee, you will assist in planning, executing, and analyzing marketing campaigns across various digital platforms. You will gain hands-on experience in SEO, social media marketing, content creation, email marketing, PPC campaigns, and data analytics. This role will help you understand consumer behavior, campaign performance metrics, and techniques to improve engagement and brand visibility.",
    requirements: [
      "Strong communication skills",
      "Basic marketing knowledge",
      "Curiosity about digital trends and analytics",
      "Ability to create engaging content",
      "Familiarity with social media platforms",
    ],
    skills: [
      "SEO: Keyword research, on-page & off-page optimization",
      "Social Media Marketing: Facebook, Instagram, LinkedIn, Twitter",
      "Content Creation: Blogs, posts, visuals, videos",
      "Email Marketing: Campaign setup, segmentation, automation",
      "Google Analytics: Tracking, reporting, insights",
      "PPC Advertising: Google Ads, social ads",
      "Branding & Online Reputation Management",
      "Marketing Strategy & Planning",
      "Data analysis and reporting",
      "Communication and copywriting skills",
    ],
    email: "hr@ibnsu.com",
  },
  {
    id: 4,
    title: "Cyber Security Trainee",
    logo: "/uplogo2.webp",
    openingDate: "2025-09-15",
    closingDate: "2025-11-30",
    description:
      "As a Cyber Security Trainee, you will gain hands-on experience in protecting computer systems, networks, and applications from cyber threats. You will learn ethical hacking, penetration testing, network security, vulnerability assessment, and risk management. This role is designed to build strong fundamentals in cybersecurity, enabling you to identify security breaches, implement preventive measures, and secure digital assets effectively.",
    requirements: [
      "Passion for IT security",
      "Basic networking knowledge",
      "Analytical mindset",
      "Attention to detail",
      "Willingness to learn advanced security techniques",
    ],
    skills: [
      "Ethical Hacking: Penetration testing, vulnerability scanning",
      "Network Security: Firewalls, VPNs, intrusion detection",
      "Web Security: OWASP, SQL injection, XSS prevention",
      "Operating Systems: Windows, Linux security basics",
      "Cryptography: Encryption, hashing, SSL/TLS",
      "Incident Response & Risk Assessment",
      "Security tools: Wireshark, Metasploit, Nmap",
      "Problem-solving and analytical thinking",
      "Policy compliance and documentation",
      "Continuous learning of cybersecurity trends",
    ],
    email: "hr@ibnsu.com",
  },
  {
    id: 5,
    title: "HR",
    logo: "/HR logo.webp",
    openingDate: "2025-09-15",
    closingDate: "2025-11-30",
    description:
      "As an HR professional, you will manage recruitment processes, employee engagement initiatives, and day-to-day HR operations. You will play a key role in fostering a positive work environment, handling performance evaluations, and implementing HR policies. This position requires strong interpersonal skills, empathy, and organizational abilities to ensure smooth operations and employee satisfaction.",
    requirements: [
      "Good communication",
      "Organizational skills",
      "Knowledge of HR practices",
      "Problem-solving and conflict resolution",
      "Ability to maintain confidentiality",
    ],
    skills: [
      "Recruitment & Talent Acquisition",
      "Employee Engagement Programs",
      "Performance Management",
      "HR Policies & Compliance",
      "Conflict Resolution & Mediation",
      "Payroll & Benefits Administration",
      "Communication & Interpersonal Skills",
      "Organizational & Planning Skills",
      "HR Software: HRMS, ATS tools",
      "Employee Training & Development",
    ],
    email: "hr@ibnsu.com",
  },
  {
    id: 6,
    title: "Sales Executive",
    logo: "/sales logo.webp",
    openingDate: "2025-09-15",
    closingDate: "2025-11-30",
    description:
      "As a Sales Executive, you will be responsible for generating leads, meeting clients, and achieving sales targets. You will work on building strong client relationships, understanding customer needs, and delivering effective solutions. This role requires excellent negotiation skills, business acumen, and the ability to adapt to changing market conditions.",
    requirements: [
      "Persuasion and negotiation skills",
      "Target-oriented mindset",
      "Good communication and presentation skills",
      "Problem-solving and critical thinking",
      "Ability to work under pressure",
    ],
    skills: [
      "Lead Generation & Prospecting",
      "Client Meetings & Relationship Management",
      "Sales Strategy & Planning",
      "Negotiation & Closing Deals",
      "Market Research & Competitor Analysis",
      "CRM Tools & Sales Software",
      "Communication & Presentation Skills",
      "Time Management & Organization",
      "Product Knowledge & Solution Selling",
      "Adaptability & Problem-Solving",
    ],
    email: "hr@ibnsu.com",
  },
  {
    id: 7,
    title: "Telecaller",
    logo: "/telecaller logo.webp",
    openingDate: "2025-09-15",
    closingDate: "2025-11-30",
    description:
      "As a Telecaller, you will engage with clients over the phone to explain services, provide assistance, and maintain accurate records. This role involves building rapport with customers, handling inquiries, and following up for potential leads. Strong communication skills, patience, and customer-centric attitude are essential to succeed in this role.",
    requirements: [
      "Good speaking skills",
      "Customer handling experience",
      "Patience and empathy",
      "Attention to detail",
      "Ability to follow scripts and protocols",
    ],
    skills: [
      "Telecalling & Customer Interaction",
      "CRM Tools & Data Management",
      "Lead Generation & Follow-ups",
      "Effective Communication Skills",
      "Problem-Solving & Conflict Resolution",
      "Product & Service Knowledge",
      "Time Management & Organization",
      "Active Listening & Persuasion",
      "Patience & Professionalism",
      "Team Collaboration & Reporting",
    ],
    email: "hr@ibnsu.com",
  },
  {
    id: 8,
    title: "Placement Officer",
    logo: "/placement officer logo.webp",
    openingDate: "2025-09-15",
    closingDate: "2025-11-30",
    description:
      "As a Placement Officer, you will be responsible for building strong industry connections, coordinating with recruiters, and assisting students in securing job opportunities. You will plan placement drives, guide students on career development, and liaise with companies to understand their hiring requirements. The role requires excellent networking, communication, and organizational skills.",
    requirements: [
      "Strong communication and networking skills",
      "Organizational and planning skills",
      "Experience in campus recruitment preferred",
      "Ability to mentor and guide students",
      "Proactive and results-driven attitude",
    ],
    skills: [
      "Networking & Relationship Building",
      "Career Guidance & Counseling",
      "Recruiter Coordination & Liaison",
      "Interview Scheduling & Preparation",
      "Event Planning & Management",
      "Communication & Presentation Skills",
      "Student Mentorship & Coaching",
      "Market & Industry Research",
      "Problem-Solving & Decision Making",
      "Data Management & Reporting",
    ],
    email: "hr@ibnsu.com",
  },
];
